### ISSUE TITLE
Clarify persistence of Network Device IDs

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-network-control#23]
We assume that when a Network Device (switch) is power-cycled, the ID included in the Network Control API /network-devices response must be persistent (and suggest that it is generated from the Chassis ID?). This would be consistent with the AMWA IS-04 [Identifier Persistence & Generation](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/5.1.%20Data%20Model%20-%20Identifier%20Mapping.md#identifier-persistence--generation) specification.

If so, perhaps this could be added to the IS-06 spec?

**Comment by garethsb** [comment]
Similarly, also suggest how Network Control _clients_ (e.g. Broadcast Controllers) could generate persistent `id` properties of the Endpoint and Network Flow resources they add.

**Comment by vsachin33** [comment]
Yes. N/W controllers should persist these ID(s) and return the same on reboot/reload ..Sachin

**Comment by vsachin33** [comment]
How clients/broadcast controller generates ID(s) is transparent to IS-06 API/network controller as long as it conforms to ID schema definition ..Sachin

**Comment by garethsb** [comment]
> How clients/broadcast controller generates ID(s) is transparent to IS-06 API/network controller as long as it conforms to ID schema definition

That's true. However persistent IDs would make resync of the BC and/or NC after reboot/reload much simpler, right?

Has the effect of different ID generation and persistence specifications on use cases with multiple BCs (or NCs for different parts of the network?) been considered?

**Comment by garethsb** [comment]
> Yes. N/W controllers should persist these ID(s) and return the same on reboot/reload ..Sachin

Are Endpoints, Network Flows, etc. also expected to be persisted by the network controller through reboot/reload?

**Comment by vsachin33** [comment]
Yes, that is my understanding. In our implementation we do that ..Sachin
