### ISSUE TITLE
Clarify pagination support

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-network-control#25]
Pagination has been adopted by the Network Control v1.0 API based on the IS-04 Query API, but seems incompletely documented in this specification.

Is the `paged` trait REQUIRED to be supported by Network Control v1.0 API implementations? It seems so as specified now. This is not the case with IS-04 Query API, which allows a 501 Not Implemented response if the API does not support pagination.

There is also no discussion of how strictly-increasing creation and update timestamps are associated with each resource type in the API. (In IS-04, the [Query Parameters - Pagination](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/2.5.%20APIs%20-%20Query%20Parameters.md#pagination) documentation describes this in detail.) Probably it can be assumed that the Network Control API must give Endpoints and Network Flows an initial creation (and update) timestamp at the initial PUT request, and the update timestamp is modified at each PATCH. It is perhaps less clear for Network Devices and Network Links how these timestamps are decided.

**Comment by vsachin33** [comment]
Looks like pagination may be copy/paste from other specs as there is no mention of endpoint/flow creation timestamp in schema. Should we add this support later? Considering these objects should be less than 1KB, we should be able to support large numbers w/o any pagination day one, regards ..Sachin

**Comment by garethsb** [comment]
Are you saying pagination is in the v1.0 spec but not supposed to be?

What scale of network is this API designed to support? Thousands of endpoints/network flows/etc.?

In IS-04, creation/update timestamps are not part of the resource data, they are metadata associated with the resources, used primarily for pagination.

**Comment by garethsb** [comment]
Resolved by #41, #43.
