### ISSUE TITLE
"Copyright issues are not considered yet."

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-network-control#29]
"Copyright issues are not considered yet."

A strange sentence to find in this specification (in [Overview - Class Diagram](https://github.com/AMWA-TV/nmos-network-control/blob/v1.0.x/docs/1.0.%20Overview.md#class-diagram)).

**Comment by vsachin33** [comment]
Should copyright policy not be consistent across NMOS/AMWA specifications? ..Sachin

**Comment by peterbrightwell** [comment]
Yes, it is a strange sentence – it dates back to ea74de46ada1a01b32cc53b41fbb2a8b4cf45b62, and is mentioned alongside the drawing tool (yEd), though I'm not sure if that's what is meant.

If it does refer to the tool, I don't see anything in the yEd trial licence that requires this sentence, or affects usage of the generated diagram. (There is mention that it may insert markers into the output.)

If it refers to IS-06 then, copyright on all the NMOS specifications belongs to AMWA, as per the LICENCE file, and all contributions have been made under the AMWA IPR policy.

In either case we can remove this.
