### ISSUE TITLE
Clarify constraints on a Network Device's LLDP configuration

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-network-control#32]
LLDP (IEEE 802.1AB) seems to allow both Chassis ID and Port ID to use a number of sub-types.

In IS-06, the JSON schemas and documentation require that a Network Device's `chassis_id` MUST be the MAC address and the `port_id` MUST be the "Ethernet Interface information" or "the `ifAlias`".

However I think the spec would benefit from a clear statement that requires the LLDP emitted by the Network Device (switch) to correspond, identifying the relevant sub-types.

**Comment by garethsb** [comment]
References:

* IS-06 [Endpoint schema](https://github.com/AMWA-TV/nmos-network-control/blob/v1.0.x/APIs/schemas/endpoint.json) says:
  * `"chassis_id"` is "as signalled in LLDP from this endpoint" (or `null`)
  * `"port_id"` is the "MAC address of the endpoint" (no mention of LLDP!)
  * `"attached_network_device.chassis_id"` is the "MAC address of the peer network device" (switch)
  * `"attached_network_device.port_id"` is the "ifAlias of the peer network device" (switch)
* IS-06 [Network Device schema](https://github.com/AMWA-TV/nmos-network-control/blob/v1.0.x/APIs/schemas/network-device.json) says:
  * `"chassis_id"` is "the MAC address of the network device" (switch)
  * `"interfaces.port_id"` is the "ifAlias of the network device" (switch), described as the "Ethernet Interface information" in the [Network Links](https://github.com/AMWA-TV/nmos-network-control/blob/v1.0.x/docs/5.0.%20Network%20Links.md#network-links) documentation
* IS-04 [Node schema](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/APIs/schemas/node.json) says:
  * `"chassis_id"` is "as signalled in LLDP" (or `null`)
  * `"port_id"` is "as signalled in LLDP or via ARP [and] must be a MAC address"
  * `"attached_network_device.chassis_id"` is the "Chassis ID [...] as signalled in LLDP"
  * `"attached_network_device.port_id"` is the "Port ID [...] as signalled in LLDP"

Given the means of discovery likely to be available to the Broadcast Controller and IS-04 Nodes, I think this implies that the IS-06 specification requires LLDP transmitted by network devices (switches) MUST use Chassis ID sub-type 4 "MAC address" and Port ID sub-type 1 "interface alias". If that were not true, the IS-06 schemas could not be met by transferring data from the IS-04 Node `"attached_network_device"` to the IS-06 Endpoint.

Is that so?

I'm not sure that the spec(s) require that IS-06 Endpoints (IS-04 Nodes) must transmit LLDP? If they do, they presumably MUST use Port ID sub-type 3 "MAC address" in order that the switch can match it to the Endpoint `"port_id"`?

**Comment by NEOAdvancedTechnology** [comment]
Gareth to make pull request for consensus position

**Comment by garethsb** [comment]
What's missing is top-level documentation in IS-06 that says IS-06 Network Device interfaces MUST transmit LLDP, signalling Chassis ID = MAC address and Port ID = ifAlias, and that an IS-06 Endpoint interface must transmit LLDP, signalling Port ID = MAC address (so far as I can see, there is no constraint in either spec on which LLDP Chassis ID subtype a Node/Endpoint should use?).

Unless I'm mistaken and IS-06 is usable _without_ LLDP?

**Comment by NEOAdvancedTechnology** [comment]
Issue is solved.
