### ISSUE TITLE
Reference to a "Futures" file which is missing from the documentation

### ISSUE THREAD

**Issue by cristian-recoseanu** [AMWA-TV/nmos-network-control#33]
In the Overview.md there seems to be a reference to a "Futures" file which I couldn't find anywhere in the repo.

> Topics for the next phase can be found in the “Futures” file in the same directory.

[in Overview.md](https://github.com/AMWA-TV/nmos-network-control/blob/v1.0.x/docs/1.0.%20Overview.md)

**Comment by garethsb** [comment]
Fixed in my PR #30.

**Comment by cristian-recoseanu** [comment]
Ah great. Sorry I missed that! Thanks @garethsb-sony

**Comment by garethsb** [comment]
@cristian-recoseanu The more eyes on this the better!! 👍
