### ISSUE TITLE
Proposed documentation structure

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-network-control#34]
Here is a proposed documentation structure, reflecting that the v1.0 specification currently assumes implementers and users to have knowledge of best practice and idioms defined in prior AMWA NMOS specifications such as IS-04 and IS-05.

The additional documentation is entirely clarification of existing function and behaviour in v1.0.

_1.0. Overview_
- move final two or three paragraphs of **Introduction** and **Class diagram** to a new _3.0. Data Model_ doc (below)
- add direct links to _2.0 APIs_ and _3.0 Data Model_

_2.0. APIs_ **(new)**
- based on IS-04 [APIs](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/2.0.%20APIs.md) or IS-05 [APIs](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/docs/2.0.%20APIs.md) docs

_2.1. APIs - Client Side Implementation_ **(new)**
_2.2. APIs - Server Side Implementation_ **(new)**
- these also based on e.g. IS-05 [APIs - Server Side Implementation Notes](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1.x/docs/2.2.%20APIs%20-%20Server%20Side%20Implementation.md)

_2.3. APIs - Query Parameters_ **(new)**
- based on IS-04 [APIs - Query Parameters](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/2.5.%20APIs%20-%20Query%20Parameters.md) to resolve #25 and related concerns about the current RAML spec for netctrl Pagination and Basic Query Parameters

_3.0. Data Model_ **(new)**
- with overview moved from _1.0. Overview_ as mentioned above

_3.1. Endpoint_ (moved from 2.0. Endpoint)
_3.2. Network Flow_ (moved from 3.0. Network Flow)
_3.3. Network Device_ (moved from 4.0. Network Device)
_3.4. Network Link_ (moved from 5.0. Network Links)

_3.5. Identifier Generation_ **(new)**
- I think a short section is warranted to resolve #23, potentially with some words based on IS-04 [Data Model - Identifier Mapping](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.3.x/docs/5.1.%20Data%20Model%20-%20Identifier%20Mapping.md)

----

Thoughts? @vsachin33 @andrewbonney @peterbrightwell

**Comment by andrewbonney** [comment]
Sounds good to me

**Comment by peterbrightwell** [comment]
Looks good -- the more we can match the structure of the other IS's the better for the future.
