### ISSUE TITLE
Question about Endpoint ip_address

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-network-control#35]
I understand an Endpoint (a network interface) is uniquely identified by its `chassis_id` and `port_id` (as well as separately by the BC-assigned `id`).

The Endpoint schema has `ip_address` as a required property which is a single IPv4 or IPv6 address.

Should an Endpoint always have one IP address? Or is it possible an Endpoint could have multiple associated IP addresses (e.g. virtualization cases)? Or currently have no assigned IP addresses?

**Comment by vsachin33** [comment]
Multiple endpoints can share same chassis_id and port_id. Endpoint schema description indicates that chassis ID can be null when not available. If there are multiple IP addresses associated w/ single physical device (endpoint) then it would be modeled as multiple virtual endpoints each w/ unique IP addresses ..Sachin

**Comment by garethsb** [comment]
Thanks, Sachin. OK, I now understand one network interface could have be registered into IS-06 Network Controller as several Endpoints with same `chassis_id`  (which may be `null`) and `port_id` (MAC address).

Therefore in order to register an Endpoint, the Broadcast Controller needs to combine properties from the IS-04 Node (`interfaces`, which one identified via the Sender or Receiver `interface_bindings`) with properties from the IS-05 Sender or Receiver active `transport_params` (`source_ip` or `interface_ip`).
