### ISSUE TITLE
"Peer port id of the new link"

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-network-control#37]
The RAML for the PUT operation on `/endpoints/{endpointId}` says "Peer port id of the new link may or may not be assigned, i.e, this is implementation dependent."

What does this mean?

The schema for Network Link says for the `port_id`: "A null value will explicitly identify this peer as an endpoint", which seems to me to make it mandatory for the Network Device peer?

**Comment by garethsb** [comment]
@vsachin33 please would you explain this one to me? Or do you think that sentence is out of date and could be removed? Thanks!

**Comment by vsachin33** [comment]
I am just guessing here - in "pre provisioning" case endpoint may not be connected hence peer port may not be present/null. This is done to reserve the bandwidth on the network ahead of time. However for put/post operation of endpoint, we shouldn't be worrying about other side so IMO this can be removed.
